-- MySQL Script generated by MySQL Workbench
-- Sat May 15 15:22:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `role` (
    `id`    INT NOT NULL AUTO_INCREMENT,
    `name`  VARCHAR(255),
    PRIMARY KEY (`id`)
);

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users`
(
    `id`         INT          NOT NULL AUTO_INCREMENT,
    `username`   VARCHAR(31)  NOT NULL,
    `email`      VARCHAR(127) NOT NULL,
    `password`   VARCHAR(255) NOT NULL,
    `phone`      VARCHAR(31)  NULL,
    `first_name` VARCHAR(63)  NOT NULL,
    `last_name`  VARCHAR(63)  NOT NULL,
    `is_active`  BOOLEAN      NOT NULL,
    `role`       INT          NOT NULL,
    CONSTRAINT `fk_user_role1`
        FOREIGN KEY (`role`)
            REFERENCES `role` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    PRIMARY KEY (`id`)
);

CREATE UNIQUE INDEX `email_UNIQUE` ON `users` (`email` ASC);
CREATE UNIQUE INDEX `username_UNIQUE` ON `users` (`username` ASC);
CREATE UNIQUE INDEX `fk_user_roles1_idx` ON `users` (`role` ASC);

-- -----------------------------------------------------
-- Table `confirm_token`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `confirm_token`
(
    `token_id`              INT             NOT NULL AUTO_INCREMENT,
    `users_id`              INT             NOT NULL,
    `confirmation_token`    VARCHAR(255)    NOT NULL,
    `created_date`          DATETIME        NOT NULL,
    CONSTRAINT `fk_confirm_token_users1`
        FOREIGN KEY (`users_id`)
            REFERENCES `users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    PRIMARY KEY (`token_id`)
);

CREATE UNIQUE INDEX `fk_confirm_token_users1_idx` ON `confirm_token` (`users_id` ASC);
